language: r
cache: packages

matrix:
  include:
  - r: release
    os: linux
    env: INSTALL_NETMHCPAN=true
  - r: devel
    os: linux
    env: INSTALL_NETMHCPAN=false

r_packages:
  - devtools
  - hunspell

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_script:
  # tcsh
  - sudo apt install tcsh
  - which tcsh
  # NetMHCpan
  - if [[ "$INSTALL_NETMHCPAN" == true ]]; then ./scripts/install_netMHCpan.sh; fi
  # LAPACK
  - sudo apt-get install liblapack-dev -y
  # proselint
  - sudo pip install proselint

after_success:
  - if [[ "$INSTALL_NETMHCPAN" == true ]]; then Rscript -e 'covr::codecov()'; fi
  - if [[ "$INSTALL_NETMHCPAN" == true ]]; then Rscript -e 'goodpractice::gp()'; fi
  - if [[ "$INSTALL_NETMHCPAN" == false ]]; then Rscript -e 'lintr::lint_package()'; fi
  - if [[ "$INSTALL_NETMHCPAN" == false ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  - # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ $(egrep -R "\"~" --include={*.R,*.Rmd}) ]]; then echo "Local file created"; exit 1; fi; fi
  - Rscript -e 'netMHCpan::netMHCpan_report()'
  - Rscript scripts/issue_3.R
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_failure:
  - Rscript -e 'remotes::install_github("tzina97/netMHCpanW")'
  - Rscript -e 'netMHCpan::netMHCpan_report()'
  - ls
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

